# Generated by Django 5.1.1 on 2024-09-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Цветовая гамма торта')),
            ],
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Начинка торта')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Форма торта')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус наличия товара')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goods/')),
                ('inscription', models.CharField(max_length=50, verbose_name='Надпись')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.color')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.filling')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.form')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.weight')),
            ],
            options={
                'verbose_name_plural': 'Торты',
                'ordering': ['filling'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepayment', models.IntegerField(verbose_name='Предоплата')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.cake')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.orderstatus')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'ordering': (['date'], ['cake'], ['order_status']),
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена товара')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goods/')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.manufacturer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.status')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
