# Generated by Django 5.1.1 on 2024-09-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name_plural': 'Цветовая гамма торта'},
        ),
        migrations.AlterModelOptions(
            name='filling',
            options={'ordering': ['name'], 'verbose_name_plural': 'Начинка торта'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['name'], 'verbose_name_plural': 'Форма торта'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['name'], 'verbose_name_plural': 'Статус заказа'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Статус наличия товара'},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['name'], 'verbose_name_plural': 'Вес торта'},
        ),
        migrations.RemoveField(
            model_name='weight',
            name='value',
        ),
        migrations.AddField(
            model_name='weight',
            name='name',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Вес торта'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название города')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.country')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Магазины')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.city')),
            ],
            options={
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
    ]
