# Generated by Django 5.1.1 on 2024-09-29 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_country_alter_color_options_alter_filling_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория торта')),
            ],
            options={
                'verbose_name_plural': 'Категория торта',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cake',
            name='filling',
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['category'], 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование ингредиента'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена,сом/кг'),
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество,кг'),
        ),
        migrations.AddField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cake.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Filling',
        ),
    ]
