# Generated by Django 5.1.1 on 2024-10-20 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_category_remove_cake_filling_alter_cake_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': (['date_create'], ['order_status'], ['shop']), 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена торта, сом'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 10, 20), verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_ready',
            field=models.DateField(default=datetime.date(2024, 10, 20), verbose_name='Дата выдачи торта'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cake.shop', verbose_name='Магазин для получения торта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.category', verbose_name='Категория торта'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.color', verbose_name='Основная цветовая гамма'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.form', verbose_name='Форма торта'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='inscription',
            field=models.CharField(max_length=50, verbose_name='Надпись на торте'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='Вставьте фото-пример'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес торта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cake.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Предоплата 50%'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Вес торта'),
        ),
    ]
