# Generated by Django 5.1.1 on 2024-10-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_order_options_remove_order_date_cake_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_create'], 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='prepayment',
        ),
        migrations.AddField(
            model_name='cake',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Предоплата 50%'),
            preserve_default=False,
        ),
    ]
