# Generated by Django 5.1.1 on 2024-10-24 12:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_alter_order_options_remove_order_prepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Начинка')),
            ],
            options={
                'verbose_name_plural': 'Начинка',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Количество ярусов торта (этажей)')),
            ],
            options={
                'verbose_name_plural': 'Количество ярусов торта (этажей)',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cake',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['filling'], 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateField(default=datetime.date(2024, 10, 24), verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ready',
            field=models.DateField(default=datetime.date(2024, 10, 24), verbose_name='Дата выдачи торта'),
        ),
        migrations.AddField(
            model_name='cake',
            name='filling',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cake.filling', verbose_name='Начинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='tier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cake.tier', verbose_name='Количество ярусов торта (этажей)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
